server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: vehicle-microservice
              uri: http://localhost:8081
              predicates:
                - Path=/api/vehicles/**
#              filters:
#                - RewritePath=/vehicles/(?<path>.*), /api/vehicles/${path}

            - id: registry-microservice
              uri: http://localhost:8082
              predicates:
                - Path=/api/registry/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
