server:
  port: 8082

spring:
  application:
    name: registry-microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/registry_microservice
    username: user
    password: user123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    showSQL: false
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

